FROM ubuntu:latest
COPY . /app
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip

WORKDIR /app
RUN pip3 install -r requirements.txt

EXPOSE 5000
ENTRYPOINT ["python3", "app.py"]